spring.application.name=student-management
spring.config.import=optional:file:.env[.properties]
# Lấy thông tin từ file .env
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Chuyển đổi hệ quản trị cơ sở dữ liệu sang PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Ứng dụng tự động khởi tạo sơ đồ cơ sở dữ liệu khi khởi động
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true